all: class.exe class_template.exe constructors.exe inheritance.exe nested.exe overload.exe polymorphism.exe private.exe purevirtual.exe staticmethod.exe this.exe virtual.exe mutable.exe

clean:
	del *.exe *.obj
