all: defaultargs.exe dynamic_cast.exe exception.exe namespace.exe newdelete.exe reference.exe static_cast.exe template.exe typeid.exe function_overload.exe function_template.exe

clean:
	del *.exe *.obj
